repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=.md]
      - id: debug-statements
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-ast
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear>=22.1.11
  - repo: https://github.com/PyCQA/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/psf/black
    rev: "22.1.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.931
    hooks:
      - id: mypy
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
  ### pylint: Let's first configure pylint.
  ### poetry: Let's wait till the hooks are released
  # - repo: https://github.com/python-poetry/poetry
  #   rev: 'master'
  #   hooks:
  #     - id: poetry-check
  #     - id: poetry-lock
  #       args: [--no-update]
