name: Publish to pypi
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Prepare env, install python dependencies
        run: |
          make build

      - name: Test
        run: |
          make test

      - name: Lint
        run: |
          make lint

      - name: Publish to test-pypi
        run: |
          poetry config pypi-token.pypi PYPI_API_TOKEN
          poetry publish
